export const MESSAGES = {
  success: "success!",
  register: "Signed Up successfully!",
  login: "Logged in successfully!",
  update: "Updated!",
  delete: "Deleted!",
  productCreated: "Product Created",
  taskCreated: "Task Created",
  taskUpdated: "Task Updated",
  taskDeleted: "Task Deleted",
  taskEdited: "Task Edited",
  blogCreated: "Blog Created",
  blogUpdated: "Blog Updated",
  blogDeleted: "Blog Deleted",
  blogEdited: "Blog Edited",
  invalidId: "Invalid Id",
  productEdited: "Product Edited",
  badRequest: "Bad Request!",
  unAuthorized: "You are not authorized!",
  user_exist: "Username already Exists!",
  userNotFound: "Username or password is In-Correct!",
  noMatchPassword: "Current Password is in-correct!",
  forbidden: "Access Denied!",
  fillInp: "Please enter valid Data!",
  fields: "Fill all fields!",
  image: "Please put image!",
  updateProfile: "Profile Updated",
  updateRole: "User Role Updated!",
  deleteAdmin: "User Deleted!",
  failed: "failed!",
  server: "Server Error!",
};

export const STATUS_CODES = {
  success: 200,
  created: 201,
  updated: 202,
  badRequest: 400,
  unAuthorized: 401,
  forbidden: 403,
  exist: 422,
  not_found: 404,
  server: 500,
};
